image:
  name: IMAGE-NAME
  tag: vVERSION
  mtag: vMASTER
  fullName: beppev/IMAGE-NAME:VERSION
  masterName: beppev/IMAGE-NAME:MASTER

weight:
  master: 100
  experimental: 0


labels:
  name: IMAGE-NAME
  version: vVERSION