image:
  name: IMAGE-NAME
  tag: vVERSION
  mtag: vMASTER
  fullName: beppev/IMAGE-NAME:VERSION
  masterName: beppev/IMAGE-NAME:MASTER

weight:
  master: 90
  experimental: 10


labels:
  name: IMAGE-NAME
  version: vVERSION
