---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.image.name }}-deployment-experimental
  namespace: stage-org1
  labels:
    name: {{ .Values.labels.name }}
    version: experimental
    app: {{ .Values.labels.app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Values.labels.name }}
      app: {{ .Values.labels.app }}
      version: experimental
  template:
    metadata:
      labels:
        name: {{ .Values.labels.name }}
        app: {{ .Values.labels.app }}
        version: experimental
    spec:
      containers:
        - name: {{ .Values.image.name }}
          image: {{ .Values.image.experimental }}
          imagePullPolicy: "Always"
          ports:
          - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.image.name }}-deployment-master
  namespace: stage-org1
  labels:
    name: {{ .Values.labels.name }}
    app: {{ .Values.labels.app }}
    version: master
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Values.labels.name }}
      app: {{ .Values.labels.app }}
      version: master
  template:
    metadata:
      labels:
        name: {{ .Values.labels.name }}
        app: {{ .Values.labels.app }}
        version: master
    spec:
      containers:
        - name: {{ .Values.image.name }}
          image: {{ .Values.image.master }}
          imagePullPolicy: "Always"
          ports:
          - containerPort: 80