---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.image.name }}-deployment-{{ .Values.image.version}}
  labels:
    name: {{ .Values.labels.name }}
    version: {{ .Values.labels.version }}
spec:
  replicas: 3
  selector:
    matchLabels:
      name: {{ .Values.labels.name }}
      version: {{ .Values.labels.version }}
  template:
    metadata:
      labels:
        name: {{ .Values.labels.name }}
        version: {{ .Values.labels.version }}
    spec:
      containers:
      - name: {{ .Values.image.name}}
        image: {{ .Values.image.name }}:{{ .Values.image.version }}
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.image.name }}-deployment-latest
  labels:
    name: {{ .Values.labels.name }}
    version: latest
spec:
  replicas: 3
  selector:
    matchLabels:
      name: {{ .Values.labels.name }}
      version: latest
  template:
    metadata:
      labels:
        name: {{ .Values.labels.name }}
        version: latest
    spec:
      containers:
      - name: {{ .Values.image.name}}
        image: {{ .Values.image.name }}:latest
        ports:
        - containerPort: 80