---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.image.name }}-deployment-{{ .Values.image.tag}}
  namespace: stage-org1
  labels:
    name: {{ .Values.labels.name }}
    version: {{ .Values.labels.tag }}
spec:
  replicas: 3
  selector:
    matchLabels:
      name: {{ .Values.labels.name }}
      version: {{ .Values.labels.tag }}
  template:
    metadata:
      labels:
        name: {{ .Values.labels.name }}
        version: {{ .Values.labels.tag }}
    spec:
      containers:
        - name: {{ .Values.image.name }}
          image: {{ .Values.image.fullName }}
          imagePullPolicy: "Always"
          ports:
          - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.image.name }}-deployment-latest
  namespace: stage-org1
  labels:
    name: {{ .Values.labels.name }}
    version: latest
spec:
  replicas: 3
  selector:
    matchLabels:
      name: {{ .Values.labels.name }}
      version: latest
  template:
    metadata:
      labels:
        name: {{ .Values.labels.name }}
        version: latest
    spec:
      containers:
        - name: {{ .Values.image.name }}
          image: {{ .Values.image.masterName }}
          imagePullPolicy: "Always"
          ports:
          - containerPort: 80