---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.image.name }}-VERSION
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.deployment.replicas}}
  selector:
    matchLabels:
      app: {{ .Values.deployment.labels.app }}
      version: {{ .Values.deployment.labels.app }}
      deployType: {{ .Values.deployment.labels.app }}
      repoName: {{ .Values.deployment.labels.app }}
      repoBranch: {{ .Values.deployment.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.labels.app }}
        version: {{ .Values.deployment.labels.app }}
        deployType: {{ .Values.deployment.labels.app }}
        repoName: {{ .Values.deployment.labels.app }}
        repoBranch: {{ .Values.deployment.labels.app }}
    spec:
      containers:
        - name: main
          image: {{ .Values.deployment.image}}
          imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
          ports:
            - containerPort: 80
            - containerPort: 443