---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.name }}-service
  namespace: stage-org1
spec:
  selector:
    name: {{ .Values.image.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.name}}-service-latest
  namespace: stage-org1
spec:
  selector:
    name: {{ .Values.image.name }}
    version: latest
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.name }}-service-{{ .Values.image.version }}
  namespace: stage-org1
spec:
  selector:
    name: {{ .Values.image.name }}
    version: {{ .Values.image.version }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80