apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.image.name }}-vservice
  namespace: stage-org1
spec:
  hosts:
    - "istio-ingress.llocal.host"
  gateways:
    - "stage-org1-gateway"
  http:
    - match:
      - headers:
          version:
            exact: {{ .Values.image.tag }}
        uri:
          prefix: "/{{.Values.image.name}}/"
        ignoreUriCase: true
      route:
        - destination:
            host: {{ .Values.image.name }}-service
            subset: experimental
    - match:
      - headers:
          version:
            exact: experimental
        uri:
          prefix: "/{{.Values.image.name}}/"
        ignoreUriCase: true
      route:
        - destination:
            host: {{ .Values.image.name }}-service
            subset: master
    - match:
      - uri:
          prefix: "/{{.Values.image.name}}/"
        irnogeUriCase: true
      route:
        - destination:
            host: {{ .Values.image.name }}-service
            subset: master
            weight: 80
        - destination:
            host: {{ .Values.image.name }}-service
            subset: experimental
            weight: 20