apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.image.name }}-service
  namespace: stage-org1
  labels:
    app: stage-org1
spec:
  hosts:
    - "istio-ingress.llocal.host"
  gateways:
    - "{{ .Values.image.name }}-gateway"
  http:
    - match:
      - headers:
          version:
            exact: experimental
        uri:
          prefix: "/{{.Values.image.name}}/"
        ignoreUriCase: true
      route:
        - destination:
            host: {{ .Values.image.name }}-service
            subset: experimental
          headers:
            request:
              add:
                subset: "experimental"
    - match:
      - headers:
          version:
            exact: experimental
        uri:
          prefix: "/{{.Values.image.name}}/"
        ignoreUriCase: true
      route:
        - destination:
            host: {{ .Values.image.name }}-service
            subset: master
          headers:
            request:
              add:
                subset: "master"
    - match:
      - uri:
          prefix: "/{{.Values.image.name}}/"
        irnogeUriCase: true
      route:
        - destination:
            host: {{ .Values.image.name }}-service
            subset: master
          weight: {{ .Values.weight.master }}
          headers:
            request:
              add:
                subset: "master"
        - destination:
            host: {{ .Values.image.name }}-service
            subset: experimental
          weight: {{ .Values.weight.experimental }}
          headers:
            request:
              add:
                subset: "experimental"
