apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.image.name }}-vservice
  namespace: stage-org1
spec:
  hosts:
    - "istio-ingress.llocal.host"
  gateways:
    - "stage-org1-gateway"
  http:
    - match:
      - headers:
          version:
            exact: {{ .Values.image.tag }}
      route:
        - destination:
            host: {{ .Values.image.name }}-service
            subset: experimental
          headers:
            request:
              add:
                subset: "experimental"
    - match:
      - headers:
          version:
            exact: experimental
      route:
        - destination:
            host: {{ .Values.image.name }}-service
            subset: master
          headers:
            request:
              add:
                subset: "master"
    - route:
        - destination:
            host: {{ .Values.image.name }}-service
            subset: master
          weight: 80
          headers:
            request:
              add:
                subset: "master"
        - destination:
            host: {{ .Values.image.name }}-service
            subset: experimental
          weight: 20
          headers:
            request:
              add:
                subset: "experimental"
