FROM golang:1.11.0-stretch as builder
COPY . /src
WORKDIR /src
RUN CGO_ENABLED=0 GOOS=linux go build -o main
#second stage
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /src/main ./main
EXPOSE 80
CMD ["./main"]